CREATE USER LPH_SYSADMIN PASSWORD = "" DEFAULT_ROLE = "SYSADMIN";
CREATE USER LPH_DEV PASSWORD = "" COMMENT = "This is the all powerful developer user";

CREATE ROLE DEVELOPER;

-- SYSADMIN role to inherit all priveleges from DEVELOPER role
GRANT ROLE DEVELOPER TO ROLE SYSADMIN;
GRANT ROLE DEVELOPER TO USER LPH_DEV;

GRANT ROLE SYSADMIN TO USER LPH_SYSADMIN;

-- Grant creation of warehouse and database and therefore almost all objects in database to role DEVELOPER
-- Cannot be executed from USERADMIN
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE "DEVELOPER";
GRANT CREATE DATABASE ON ACCOUNT TO ROLE "DEVELOPER";