-- Create USERADMIN account and SYSADMIN accounts from ACCOUNTADMIN
CREATE USER LPH_SYSADMIN PASSWORD = "*****" DEFAULT_ROLE = "SYSADMIN";
CREATE USER LPH_USERADMIN PASSWORD = "*****" DEFAULT_ROLE = "USERADMIN";
GRANT ROLE SYSADMIN TO USER LPH_SYSADMIN;
GRANT ROLE USERADMIN TO USER LPH_USERADMIN;

-- Run user and role object related tasks from USERADMIN role
CREATE USER LPH_DEV PASSWORD = "*****" COMMENT = "This is the all powerful developer user";
CREATE USER LPH_READONLY PASSWORD = "*****" COMMENT = "This is for analyst users, where only read only access is required";

CREATE ROLE DEVELOPER;
CREATE ROLE ACCESS;

-- Set up privilege hierarchy
GRANT ROLE ACCESS TO ROLE DEVELOPER;
GRANT ROLE DEVELOPER TO ROLE SYSADMIN;

-- Provision roles to users
GRANT ROLE ACCESS TO USER LPH_READONLY;
GRANT ROLE DEVELOPER TO USER LPH_DEV;

-- Use SYSADMIN here as USER_ADMIN cannot grant privileges on the database and warehouse level
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE "DEVELOPER";
GRANT CREATE DATABASE ON ACCOUNT TO ROLE "DEVELOPER";

-- Run from DEVELOPER role
CREATE WAREHOUSE TRANSFORMER;
CREATE DATABASE RAW;
CREATE DATABASE STAGING;
CREATE DATABASE MARTS;

-- Run from SYSADMIN role
GRANT USAGE ON WAREHOUSE TRANSFORMER TO ROLE "ACCESS";
GRANT USAGE ON DATABASE MARTS TO ROLE "ACCESS";
